version: '3'
services:
  myregistry:
    image: registry:2
    ports:
      - "5001:5000"  # Host port 5001 maps to container port 5000
    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"  # Listen on all network interfaces on port 5000
      REGISTRY_HTTP_TLS_DISABLED: "true"   # Disable TLS (HTTPS) support
    volumes:
      - ./certs:/certs  # Ensure this directory contains domain.crt and domain.key
    networks:
      - my_network

  imageservice:
    build:
      context: .
      args:
        CERTS_DIR: ./certs  # Assign the value to the CERTS_DIR build argument
    ports:
      - "8080:8080"
    depends_on:
      - myregistry
    networks:
      - my_network
    environment:
      - REGISTRY_HOST=myregistry
      - REGISTRY_PORT=5000

networks:
  my_network:
    driver: bridge
