spring:
  application:
    name: ImageService
  cloud:
    gateway:
      routes:
        - id: registry
          uri: http://myregistry:5000
          predicates:
            - Path=/v2/**

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: mthn.trkmn123
    key-store-type: PKCS12


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG